title: Lab Website Template
subtitle: by the Greene Lab
description: An easy-to-use, flexible website template for labs, with automatic citations, GitHub tag imports, pre-built components, and more.
header_image: images/background.jpg
footer_image: images/background.jpg
page_background: /images/1728192334348.jpg
page_panel_opacity: 0.85
links:
  email: contact@your-lab.com
  orcid: 0000-0001-8713-9213
  google-scholar: ETJoidYAAAAJ
  github: your-lab
  twitter: YourLabHandle
  linkedin: ''
  youtube: YourLabChannel
